### ISSUE TITLE
armor stands with items/blocks on their head

### ISSUE THREAD

**Issue by LGCoding** [GeyserMC/GeyserOptionalPack#26]
If you have an armorstand with an item on its head that does not normally go on an armorstand’s head the item is not displayed.

**Comment by Kas-tle** [comment]
This can be done on a per item basis, but from a practical standpoint this is not something that could be added to the pack. This is because it would require an individual attachable for every item, leading to hundreds of attachables. For info on how to implement an such attachables on a per item basis, see the discussion here: https://github.com/GeyserMC/Geyser/issues/3373
